### ISSUE TITLE
Show warning / error instead of silent exit if bbswitch not found

### ISSUE THREAD

**Issue by dm0** [dm0/nvidia-power-manager#3]
Currently application silently exits if it can't read `/proc/acpi/bbswitch`. 

Corresponding message should be printed to the console.

**Comment by dm0** [comment]
Resolved in 1da18c7.

**Comment by lestcape** [comment]
Interesting, but i think it should be more dramatically than just that... Because:
https://github.com/Bumblebee-Project/bbswitch/issues/164

Also in my case, after `sudo modprobe bbswitch`, the indicator is started, but the '**Power Off GPU**' action do not disable the nvidia driver really. Logs continues showing me that is enable and not error was printed to inform me that the action fail, also of course i have not hint about the possible problem:

```
2020-01-22 04:32:16,011: DEBUG: refresh: updating device state
2020-01-22 04:32:16,011: DEBUG: is_nvidia_on: bbswitch state: 0000:01:00.0 ON
```

**Comment by dm0** [comment]
Thanks, the point about `bswitch` autoloading is missing in the readme.

About disabling.  
The "Power Off GPU" action calls `/usr/lib/nvidia-power-manager/gpuswitcher` script with "off" argument.  
The script in turn does the following:
* `modprobe -r -a nvidia` 
* If after the previous command the module is still there (checks via `lsmod`), then it tries `rrmmod nvidia`
* Toggles power via `bbswitch`: `tee /proc/acpi/bbswitch <<< OFF`

Please try the first step and look for any errors. Check if `nvidia` module is there and then try the second step (again, looking for any errors). If after the second step `nvidia` module is still loaded, it doesn't make sense to call `bbswitch` — it will not turn off GPU. But in this case there should be some errors about module unloading.
